{% set name = "thermostate" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/thermostate-{{ version }}.tar.gz
  sha256: a9f5a34560bac87684bf184f7f6c4326425b60313a024c38bcee8dcb2a22e6ec

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - coolprop >=6.1.0
    - matplotlib-base >=2.0
    - numpy >=1.15
    - pint <0.20,>=0.9
    - python >=3.7

test:
  imports:
    - thermostate

about:
  home: https://thermostate.readthedocs.io/
  summary: A package to manage thermodynamic states
  dev_url: https://github.com/bryanwweber/thermostate
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - bryanwweber
